import { describe, expect, it } from 'vitest'
import abilityProfileGroupPage from './AbilityProfileGroupPage.vue?raw'
import simpleRadarChart from './components/SimpleRadarChart.vue?raw'

describe('ability profile group page layout', () => {
  it('frames the group portrait as an observation page instead of a diagnosis page', () => {
    expect(abilityProfileGroupPage).toContain('groupObservation')
    expect(abilityProfileGroupPage).toContain('overview-hero')
    expect(abilityProfileGroupPage).toContain('画像概览')
    expect(abilityProfileGroupPage).toContain('competentOrAboveRate')
    expect(abilityProfileGroupPage).toContain('radarReadingItems')
    expect(abilityProfileGroupPage).toContain('结构特征')
    expect(abilityProfileGroupPage).toContain('相对较高维度')
    expect(abilityProfileGroupPage).toContain('相对较低维度')
    expect(abilityProfileGroupPage).toContain('建议关注对象')
    expect(abilityProfileGroupPage).not.toContain('诊断结论')
    expect(abilityProfileGroupPage).not.toContain('groupDiagnosis')
    expect(abilityProfileGroupPage).not.toContain('短板集中')
    expect(abilityProfileGroupPage).not.toContain('建议动作')
    expect(abilityProfileGroupPage).not.toContain('达标教师占比')
    expect(abilityProfileGroupPage).toContain('evidence-grid')
    expect(abilityProfileGroupPage).toContain('SimpleRadarChart')
    expect(abilityProfileGroupPage).toContain('雷达结构')
    expect(abilityProfileGroupPage).not.toContain('dimension-bars')
    expect(abilityProfileGroupPage).not.toContain('维度对比')
    expect(abilityProfileGroupPage).toContain('radar-reading-panel')
    expect(abilityProfileGroupPage).toContain('读图摘要')
  })

  it('keeps dimension details observational instead of dumping index composition text', () => {
    expect(abilityProfileGroupPage).toContain('维度观察')
    expect(abilityProfileGroupPage).toContain('观察说明')
    expect(abilityProfileGroupPage).toContain('getDimensionObservation')
    expect(abilityProfileGroupPage).not.toContain('维度诊断')
    expect(abilityProfileGroupPage).not.toContain('诊断定位')
    expect(abilityProfileGroupPage).not.toContain('指数构成')
    expect(abilityProfileGroupPage).not.toContain('prop="composition"')
  })

  it('makes the radar chart the primary structure map for group portrait', () => {
    expect(abilityProfileGroupPage).toContain('radar-structure-panel')
    expect(abilityProfileGroupPage).toContain('radar-reading-panel')
    expect(abilityProfileGroupPage).toContain('basic-ability-status')
    expect(abilityProfileGroupPage).toContain('基本能力')
    expect(abilityProfileGroupPage).toContain('达标')
    expect(abilityProfileGroupPage).toContain('结构特征')
    expect(abilityProfileGroupPage).toContain('建议查看')
    expect(abilityProfileGroupPage).toContain(':dimension-colors="dimensionColors"')
    expect(abilityProfileGroupPage).toContain(':stage-rings="radarStageRings"')
    expect(abilityProfileGroupPage).toContain('center-label="基本能力"')
    expect(abilityProfileGroupPage).toContain('center-status="达标"')
    expect(abilityProfileGroupPage).toContain('radar-map-frame')
    expect(abilityProfileGroupPage).toContain('radar-stage-guide')
    expect(abilityProfileGroupPage).toContain('stage-name')
    expect(abilityProfileGroupPage).toContain(':size="460"')
    expect(abilityProfileGroupPage).toContain('visibleRadarReadingItems')
    expect(abilityProfileGroupPage).toContain("item.key !== 'strongest'")
    expect(abilityProfileGroupPage).toContain('相对较高：${strongestDimension.value.dimension}')
    expect(abilityProfileGroupPage).not.toContain('overview-metrics')
  })

  it('renders radar stages and dimension colors as chart semantics', () => {
    expect(simpleRadarChart).toContain('stageRings')
    expect(simpleRadarChart).toContain('dimensionColors')
    expect(simpleRadarChart).toContain('centerLabel')
    expect(simpleRadarChart).toContain('centerStatus')
    expect(simpleRadarChart).toContain('radar-stage-label')
    expect(simpleRadarChart).toContain('radar-stage-band')
    expect(simpleRadarChart).toContain('axisLines')
    expect(simpleRadarChart).toContain('radar-axis-line')
    expect(simpleRadarChart).toContain('axisLabelRadius')
    expect(simpleRadarChart).toContain('radar-score-label')
    expect(simpleRadarChart).toContain('stageFillOpacity = 0.18')
    expect(simpleRadarChart).toContain('radar-center-core')
    expect(simpleRadarChart).toContain('radar-axis-dot')
    expect(simpleRadarChart).toContain('r="24"')
    expect(simpleRadarChart).toContain('r="18"')
    expect(simpleRadarChart).toContain('新手')
    expect(simpleRadarChart).toContain('胜任')
    expect(simpleRadarChart).toContain('骨干')
    expect(simpleRadarChart).toContain('名师')
  })
})
