export const practiceTrackingPageReview = {
  route: '/admin/practice/tracking',
  title: '发展活动 / 企业实践年度跟踪',
  goal: '跟踪教师年度企业实践完成情况，提醒未启动申请教师，并从跟踪记录进入实践记录。',
  screenshot: '效果图/管理PC端/4发展活动/3企业实践/管理端PC｜企业实践｜年度实践跟踪.png',
  sections: [
    '年度完成情况统计',
    '当前办理情况统计',
    '教师实践跟踪筛选栏',
    '教师实践跟踪表格',
    '选中教师摘要',
    '导出任务提示',
  ],
  dataRules: [
    '跟踪列表、实践记录和导出任务来自 practiceStore。',
    '年度完成情况由 practiceState.trackings 的 remainingDays 计算。',
    '当前办理情况由 trackings 和 records 的状态计算。',
    '筛选结果由院系、专业、完成情况、当前状态和搜索关键字共同决定。',
  ],
  interactions: [
    '查询将搜索框内容应用到筛选关键字并显示筛选反馈。',
    '重置恢复默认筛选并显示反馈。',
    '提醒申请调用 remindPracticeApplication() 并选中当前教师。',
    '查看记录跳转 /admin/practice/records?recordId=...；若无记录，显示降级反馈。',
    '导出名单创建并完成导出任务，空筛选结果应生成失败反馈。',
  ],
  formRules: [],
  checklist: [
    '统计卡、筛选栏、表格和摘要与效果图基本一致',
    '筛选、查询、重置能更新列表',
    '提醒申请写入共享状态反馈',
    '查看记录能进入实践记录页并定位记录',
    '导出任务有成功或失败状态反馈',
  ],
}
