export const practiceRecordPageReview = {
  route: '/admin/practice/records',
  title: '发展活动 / 企业实践记录总览',
  goal: '管理企业实践记录，跟踪材料状态、提醒补材料、确认归档，并进入成长档案处理记录。',
  screenshot: '效果图/管理PC端/4发展活动/3企业实践/管理端PC｜企业实践｜实践记录总览.png',
  sections: [
    '实践状态统计',
    '记录筛选栏',
    '企业实践记录表格',
    '选中记录摘要',
    '导出任务提示',
  ],
  dataRules: [
    '实践记录、导出任务和操作反馈来自 practiceStore。',
    'recordId query 参数用于初始化选中记录。',
    '统计卡由 practiceState.records 的 currentStatus 计算。',
    '筛选结果由院系、实践状态、计入 30 天状态和搜索关键字共同决定。',
    '确认归档必须调用 confirmPracticeArchive() 并生成成长档案待确认处理记录。',
  ],
  interactions: [
    '查询将搜索框内容应用到筛选关键字并显示筛选反馈。',
    '重置恢复默认筛选并显示反馈。',
    '查看只在当前表格定位记录。',
    '提醒补材料调用 remindPracticeMaterial()。',
    '确认归档调用 confirmPracticeArchive()，查看档案跳转成长档案处理页。',
    '导出记录创建并完成导出任务，空筛选结果应生成失败反馈。',
  ],
  formRules: [],
  checklist: [
    '统计卡、筛选栏、记录表和摘要与效果图基本一致',
    'recordId query 能初始化选中记录',
    '筛选、查询、重置能更新记录列表',
    '提醒补材料和确认归档写入共享状态',
    '确认归档后可进入成长档案处理队列查看',
  ],
}
