import type { PracticeApplication, PracticeExportTask, PracticeRecord, PracticeState, PracticeTracking } from '@/domain/admin/practice'

export const initialApplications: PracticeApplication[] = [
  {
    id: '1',
    teacher: '林老师',
    teacherNo: 'T202401015',
    department: '智能制造学院',
    annualStatus: '本年度已计入 18 天，还差 12 天',
    remainingDays: 12,
    company: '山西智能装备有限公司',
    position: '工艺改进实践',
    practicePeriod: '2026-07-01 至 2026-07-15，预计 15 天',
    estimatedDays: '15',
    status: '待审核',
    applyTime: '2026-06-20 10:35',
  },
  {
    id: '2',
    teacher: '赵老师',
    teacherNo: 'T202401021',
    department: '智能制造学院',
    annualStatus: '本年度已计入 10 天，还差 20 天',
    remainingDays: 20,
    company: '济南数控技术有限公司',
    position: '生产线调试实践',
    practicePeriod: '2026-07-05 至 2026-07-25，预计 21 天',
    estimatedDays: '21',
    status: '待审核',
    applyTime: '2026-06-18 16:20',
  },
  {
    id: '3',
    teacher: '王老师',
    teacherNo: 'T202301009',
    department: '信息工程学院',
    annualStatus: '本年度已计入 20 天，还差 10 天',
    remainingDays: 10,
    company: '青岛工业机器人有限公司',
    position: '现场调试实践',
    practicePeriod: '2026-06-10 至 2026-06-22，预计 12 天',
    estimatedDays: '12',
    status: '已同意',
    applyTime: '2026-06-08 09:15',
  },
  {
    id: '4',
    teacher: '陈老师',
    teacherNo: 'T202401030',
    department: '汽车工程学院',
    annualStatus: '本年度已计入 8 天，还差 22 天',
    remainingDays: 22,
    company: '山木智能装备集团',
    position: '岗位实践',
    practicePeriod: '2026-07-10 至 2026-07-30，预计 21 天',
    estimatedDays: '21',
    status: '退回修改',
    applyTime: '2026-06-16 11:05',
  },
  {
    id: '5',
    teacher: '孙老师',
    teacherNo: 'T202301017',
    department: '财经商贸学院',
    annualStatus: '本年度已计入 15 天，还差 15 天',
    remainingDays: 15,
    company: '济南商贸股份有限公司',
    position: '电商运营实践',
    practicePeriod: '2026-06-20 至 2026-07-04，预计 15 天',
    estimatedDays: '15',
    status: '已撤回',
    applyTime: '2026-06-14 14:40',
  },
  {
    id: '6',
    teacher: '周老师',
    teacherNo: 'T202401008',
    department: '智能制造学院',
    annualStatus: '本年度已计入 5 天，还差 25 天',
    remainingDays: 25,
    company: '烟台机械制造有限公司',
    position: '设备维护实践',
    practicePeriod: '2026-07-15 至 2026-08-13，预计 30 天',
    estimatedDays: '30',
    status: '待审核',
    applyTime: '2026-06-21 08:50',
  },
]

export const initialTrackings: PracticeTracking[] = [
  {
    id: '1',
    teacher: '林老师',
    department: '智能制造学院',
    major: '机电一体化技术',
    completionStatus: '未完成 30 天，已计入 18 天，还差 12 天',
    currentProgress: '未启动申请',
    recentAction: '暂无本年度申请',
    requiredDays: 30,
    completedDays: 18,
    remainingDays: 12,
  },
  {
    id: '2',
    teacher: '王老师',
    department: '智能制造学院',
    major: '工业机器人技术',
    completionStatus: '未完成 30 天，已计入 20 天，还差 10 天',
    currentProgress: '实践中',
    recentAction: '06-10 已提交实践申请',
    requiredDays: 30,
    completedDays: 20,
    remainingDays: 10,
  },
  {
    id: '3',
    teacher: '赵老师',
    department: '智能制造学院',
    major: '机器人一体化专业',
    completionStatus: '未完成 30 天，已计入 20 天，还差 10 天',
    currentProgress: '待审核申请',
    recentAction: '06-18 提交申请',
    requiredDays: 30,
    completedDays: 20,
    remainingDays: 10,
  },
  {
    id: '4',
    teacher: '陈老师',
    department: '电子信息学院',
    major: '软件技术专业',
    completionStatus: '已完成 30 天',
    currentProgress: '已完成',
    recentAction: '05-22 实践记录已归档',
    requiredDays: 30,
    completedDays: 30,
    remainingDays: 0,
  },
]

export const initialRecords: PracticeRecord[] = [
  {
    id: '1',
    applicationId: '1',
    teacher: '林老师',
    department: '智能制造学院',
    major: '机电一体化技术',
    company: '山西智能装备有限公司',
    position: '工艺改进实践',
    practicePeriod: '2026-07-01 至 2026-07-15 / 15 天',
    materialStatus: '日志完整 | 总结待提交 | 评价待上传',
    currentStatus: '待提交总结',
    countedDays: '暂未计入',
    recentAction: '07-15 完成实践',
  },
  {
    id: '2',
    applicationId: '3',
    teacher: '王老师',
    department: '智能制造学院',
    major: '工业机器人技术',
    company: '青岛工业机器人有限公司',
    position: '现场调试实践',
    practicePeriod: '2026-06-10 至 2026-06-22 / 12 天',
    materialStatus: '日志完整 | 总结已交 | 评价已上传',
    currentStatus: '待归档确认',
    countedDays: '归档后计入',
    recentAction: '06-24 提交总结',
  },
  {
    id: '3',
    teacher: '陈老师',
    department: '智能制造学院',
    major: '数控技术',
    company: '山西智能装备集团',
    position: '岗位实践',
    practicePeriod: '2026-05-01 至 2026-05-30 / 30 天',
    materialStatus: '材料完整',
    currentStatus: '已归档',
    countedDays: '已计入',
    recentAction: '06-02 已归档',
  },
  {
    id: '4',
    teacher: '赵老师',
    department: '电子信息学院',
    major: '软件技术',
    company: '济南智联科技有限公司',
    position: '项目开发实践',
    practicePeriod: '2026-07-08 至 2026-07-28 / 21 天',
    materialStatus: '日志待补 | 总结未提交 | 评价待上传',
    currentStatus: '实践中',
    countedDays: '暂未计入',
    recentAction: '07-18 提交日报',
  },
  {
    id: '5',
    teacher: '孙老师',
    department: '智能制造学院',
    major: '应用电子技术',
    company: '济南高端制造有限公司',
    position: '产线优化实践',
    practicePeriod: '2026-06-01 至 2026-06-18 / 18 天',
    materialStatus: '日志完整 | 总结已交 | 评价待上传',
    currentStatus: '待企业评价',
    countedDays: '暂未计入',
    recentAction: '06-19 企业反馈缺失',
  },
]

export function createInitialPracticeState(): PracticeState {
  return {
    applications: cloneApplications(initialApplications),
    trackings: cloneTrackings(initialTrackings),
    records: cloneRecords(initialRecords),
    exportTasks: [],
    operationMessage: '',
  }
}

export function cloneApplications(applications: PracticeApplication[]) {
  return applications.map(item => ({ ...item }))
}

export function cloneTrackings(trackings: PracticeTracking[]) {
  return trackings.map(item => ({ ...item }))
}

export function cloneRecords(records: PracticeRecord[]) {
  return records.map(item => ({ ...item }))
}

export function cloneExportTasks(tasks: PracticeExportTask[]) {
  return tasks.map(item => ({ ...item }))
}
